[package]
name = "portify"
version = "1.0.5"
edition = "2021"

[dependencies]
pnet = "0.34"
libc = "0.2"
indicatif = "0.17"
console = "0.15"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
